let form = document.createElement('form');
form.method = 'POST';
form.enctype = 'multipart/form-data';
form.action = '/api/avatar/update';
let input = document.createElement('input');
input.type = 'file';
input.name = 'avatar';
let ext = document.createElement('input');
ext.type = 'text';
ext.name = 'ext';
let submit = document.createElement('input');
submit.type = 'submit';
form.appendChild(input);
form.appendChild(ext);
form.appendChild(submit);
document.body.appendChild(form);
form.style.paddingTop = '100px';