export const LOGIN_REQUEST_LOGIN_TYPE_USERNAME = 1;
export const LOGIN_REQUEST_LOGIN_TYPE_USERID = 2;
export let QUERY_USER_REQUEST_QUERY_COL_USERNAME = 1;
export let QUERY_USER_REQUEST_QUERY_COL_USERID = 2;
